### ISSUE TITLE
Switch to Webpack

### ISSUE THREAD

**Issue by tj** [tj/react-fatigue-dev#2]
Maybe. Browserify's stuff doesn't seem as useful for hacking on d3 components / css, still need to refresh, unless I'm missing something.

**Comment by rafaelrinaldi** [comment]
Maybe [`browserify-hmr`](https://github.com/AgentME/browserify-hmr) or [Browsersync](https://www.browsersync.io) can help?

**Comment by tj** [comment]
HmmM I'll take a peek at browsersync sometime soon! thanks for the link. Browserify HMR seems fine for React stuff but I webpack seemed to handle d3/css etc better.

**Comment by oieduardorabelo** [comment]
@tj this can be a start, https://github.com/oieduardorabelo/react-fatigue-webpack

basic loaders for js and css, but easy to expand

**Comment by tj** [comment]
@oieduardorabelo nice I'll have to give that a try! I abandoned HMR all together in my apps haha, too many issues, but it would still be handy for modules.
